language: dart
sudo: false
dart:
  - dev
  - stable
cache:
  directories:
    - $HOME/.pub-cache
before_script: dart ./tool/sanity_check.dart
dart_task:
  - dartanalyzer
  - pub run test -p vm
  - dartfmt
matrix:
  # Only run dartfmt checks with stable.
  exclude:
    - dart: dev
      dart_task: dartfmt
    - dart: dev
      dart_task: dartanalyzer
